services:
  mongodb:
    image: 'mongo:8.0'
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    networks:
      - mongodb_network

    volumes:
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongo-express:
    image: 'mongo-express:1.0.2'
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017

    networks:
      - mongodb_network
    depends_on:
      mongodb:
        condition: service_healthy

networks:
  mongodb_network:
    driver: bridge
    name: mongodb-network

volumes:
  mongodb-data:
    driver: local
    name: mongodb-data
  mongodb-log:
    driver: local
    name: mongodb-log
  # web:
  #   build:
  #     context: ../
  #   env_file:
  #     - ./.env
  #   logging:
  #     driver: "json-file"
  #     options:
  #         max-size: "1g"
  #   volumes:
  #     - ../:/app
  #   depends_on:
  #     - pg
  #   command: uvicorn app:app --host 0.0.0.0 --port 80

  # bot:
  #   build:
  #     context: ../
  #   env_file:
  #     - ./.env
  #   logging:
  #     driver: "json-file"
  #     options:
  #         max-size: "1g"
  #   volumes:
  #     - ../:/app
  #   command: python bot.py

  # nginx:
  #   image: nginx:1.25.3
  #   container_name: nginx
  #   volumes:
  #     - ./nginx.conf/:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web
